In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import time
import copy
import datetime
# Do you wanna see?
verbose = True

import sys
sys.path.append('../')

from utils.data_extraction import load_data
from utils.data_cleaning import HFDataCleaning
from utils.generate_features import candleCreateNP_vect_final, generateFeatures_final
from utils.preprocessing_features_and_labels import extract_labels

### Load data etc

In [2]:
# print(os.listdir())
try:
    path = 'a:/taqhdf5'  #'a:/taqhdf5'
    os.listdir(path)
except:
    path = 't:/taqhdf5'  #'a:/taqhdf5'
    os.listdir(path)    
# allFiles = os.listdir(path)
# print(len(allFiles), allFiles[:5], allFiles[-5:])
# print(allFiles[-10:])

#dates = np.array(['2020040' + str(i) if i < 10 else '202004' + str(i) for i in np.arange(1,32)]).astype(int)
dates = np.array(['20200401','20200402']).astype(int)

# Provide a list of tickers of interest
tickers = ['GOOG']#'MSFT'

# Do we need data on trades, quotes or both?
dataNeeded = 'trades' # 'trades', 'quotes' or 'both'

# run load_data()
if dataNeeded == 'trades':
    tradeData = load_data(dates, tickers, dataNeeded, path, verbose)
elif dataNeeded == 'quotes':
    quoteData = load_data(dates, tickers, dataNeeded, path, verbose)
elif dataNeeded == 'both':
    tradeData, quoteData = load_data(dates, tickers, dataNeeded, path, verbose)

['.ipynb_checkpoints', 'preprocessing.ipynb', 'testing_and_comparing_candlesticks.ipynb', 'testing_features.ipynb', 'testing_preprocessing_features_and_labels.ipynb']
8515 ['taq_19930315.h5', 'taq_19930104.h5', 'taq_19930317.h5', 'taq_19930105.h5', 'taq_19930316.h5'] ['taqquote_20200522.h5', 'taqquote_20200526.h5', 'taqquote_20200527.h5', 'taqquote_20200528.h5', 'taqquote_20200529.h5']
['taqquote_20200515.h5', 'taqquote_20200518.h5', 'taqquote_20200519.h5', 'taqquote_20200520.h5', 'taqquote_20200521.h5', 'taqquote_20200522.h5', 'taqquote_20200526.h5', 'taqquote_20200527.h5', 'taqquote_20200528.h5', 'taqquote_20200529.h5']
##### Date range #####

Date, Min: 20200401
Date, Max: 20200402

##### Data Extraction begins #####

trade data is being extracted..

### Trade Data ###

The raw H5 trade file contains:  ['TradeIndex', 'Trades'] 

Ticker Information:  (b'GOOG            ', 26900500, 71427) 

Sneak peak of the data

            utcsec ex  cond  volume    price TradeStopStockIndicator c

In [3]:
DATA_SAMPLE = 'full' # or 'stable'

if DATA_SAMPLE == 'stable':
    # P1 is used for keeping data within [9.5, 16]
    cleanedData = HFDataCleaning(['P1','p2','t1','p3'],tradeData,'trade',['q','d'])
elif DATA_SAMPLE == 'full':
    # P1_2 is used for keeping data within [9, 16.5]
    cleanedData = HFDataCleaning(['P1_2','p2', 't1', 'p3'],tradeData,'trade',['q','d'])    

In [4]:
tradeData[tradeData.Timestamp.dt.hour == 9] 

utcsec ex  cond  volume      price TradeStopStockIndicator corr  \
877   32402041512373  D  @ TI      30  1124.4600                           00   
878   32406408120050  K  @ TI       2  1125.7000                           00   
879   32406409053327  K  @ TI       1  1125.5000                           00   
880   32406409838624  K  @ TI       4  1125.0000                           00   
881   32406410609648  K  @ TI       1  1124.5000                           00   
...              ... ..   ...     ...        ...                     ...  ...   
9303  35992120837241  Q  @F I       4  1104.0000                           00   
9304  35992120855585  Q  @  I       6  1104.0000                           00   
9305  35996926419906  D  @  I      20  1104.4705                           00   
9306  35998831193089  Y  @        100  1104.0300                           00   
9307  35999484715738  D  @  I       6  1103.6800                           00   

      TradeSequenceNumber TradeID SourceOfTrade TradeReportingFacility  \
877                 25795      23             N                      N   
878                 25808     257             N                          
879                 25809     258             N                          
880                 25810     259             N                          
881                 25811     260             N                          
...                   ...     ...           ...                    ...   
9303               555241    3622             N                          
9304               555242    3623             N                          
9305               555855     404             N                      N   
9306               556030      93             N                          
9307               556126    1305             N                      Q   

      ParticipantTime         TRFTime TTE      Date  \
877    32402038000000  32402041146104   0  20200401   
878    32406407880000              99   0  20200401   
879    32406408841000              99   0  20200401   
880    32406409633000              99   0  20200401   
881    32406410405000              99   0  20200401   
...               ...             ...  ..       ...   
9303   35992120811312              99   1  20200402   
9304   35992120836815              99   0  20200402   
9305   35996921000000  35996926061224   0  20200402   
9306   35998830988000              99   0  20200402   
9307   35999482000000  35999484677286   0  20200402   

                      Timestamp TSRemainder  Hour  Minute Ticker  
877  2020-04-01 09:00:02.041512         373     9       0   GOOG  
878  2020-04-01 09:00:06.408120         050     9       0   GOOG  
879  2020-04-01 09:00:06.409053         327     9       0   GOOG  
880  2020-04-01 09:00:06.409838         624     9       0   GOOG  
881  2020-04-01 09:00:06.410609         648     9       0   GOOG  
...                         ...         ...   ...     ...    ...  
9303 2020-04-02 09:59:52.120837         241     9      59   GOOG  
9304 2020-04-02 09:59:52.120855         585     9      59   GOOG  
9305 2020-04-02 09:59:56.926419         906     9      59   GOOG  
9306 2020-04-02 09:59:58.831193         089     9      59   GOOG  
9307 2020-04-02 09:59:59.484715         738     9      59   GOOG  

[19313 rows x 20 columns]

In [5]:
tradeData[(tradeData.Timestamp.dt.hour == 16) & (tradeData.Timestamp.dt.minute == 29)] 
# no data from exchange Q after 16:22:30

utcsec ex  cond  volume    price TradeStopStockIndicator corr  \
71179  59359931498154  D  @ TI      21  1105.62                           00   
56472  59377688654669  D  @ TI       1  1119.00                           00   

       TradeSequenceNumber TradeID SourceOfTrade TradeReportingFacility  \
71179              4328878   16774             N                      Q   
56472              4768036    3413             N                      N   

       ParticipantTime         TRFTime TTE      Date  \
71179   59359924000000  59359931442725   0  20200401   
56472   59377685000000  59377688294896   0  20200402   

                       Timestamp TSRemainder  Hour  Minute Ticker  
71179 2020-04-01 16:29:19.931498         154    16      29   GOOG  
56472 2020-04-02 16:29:37.688654         669    16      29   GOOG

In [6]:
cleanedData

utcsec ex  cond  volume      price TradeStopStockIndicator  \
0      32402041512373  D  @ TI      30  1124.4600                           
1      32444512198659  D  @ TI       6  1124.2033                           
2      32485885409069  Q  @ TI      30  1124.6200                           
3      32486612971716  Q  @ TI      30  1124.5100                           
4      32519261072977  Q  @ TI       1  1125.7400                           
...               ... ..   ...     ...        ...                     ...   
80256  59248864969186  D  @ TI       2  1119.0900                           
80257  59267986413301  D  @ TI       2  1121.5300                           
80258  59283857808619  D  @ TI      17  1119.0900                           
80259  59303907331488  D  @ TI      83  1119.0000                           
80260  59377688654669  D  @ TI       1  1119.0000                           

      corr  TradeSequenceNumber TradeID SourceOfTrade TradeReportingFacility  \
0       00                25795      23             N                      N   
1       00                26270      24             N                      N   
2       00                26476     293             N                          
3       00                26492     294             N                          
4       00                26668     295             N                          
...    ...                  ...     ...           ...                    ...   
80256   00              4767733    3411             N                      N   
80257   00              4767764    3412             N                      N   
80258   00              4767797   11777             N                      Q   
80259   00              4767844   11778             N                      Q   
80260   00              4768036    3413             N                      N   

       ParticipantTime         TRFTime TTE      Date  \
0       32402038000000  32402041146104   0  20200401   
1       32444509000000  32444511840333   0  20200401   
2       32485885387917              99   0  20200401   
3       32486612950358              99   0  20200401   
4       32519261050258              99   0  20200401   
...                ...             ...  ..       ...   
80256   59248862000000  59248864611855   0  20200402   
80257   59267983000000  59267986052845   0  20200402   
80258   59283855000000  59283857769578   0  20200402   
80259   59303905000000  59303907291316   0  20200402   
80260   59377685000000  59377688294896   0  20200402   

                       Timestamp TSRemainder  Hour  Minute Ticker  
0     2020-04-01 09:00:02.041512         373     9       0   GOOG  
1     2020-04-01 09:00:44.512198         659     9       0   GOOG  
2     2020-04-01 09:01:25.885409         069     9       1   GOOG  
3     2020-04-01 09:01:26.612971         716     9       1   GOOG  
4     2020-04-01 09:01:59.261072         977     9       1   GOOG  
...                          ...         ...   ...     ...    ...  
80256 2020-04-02 16:27:28.864969         186    16      27   GOOG  
80257 2020-04-02 16:27:47.986413         301    16      27   GOOG  
80258 2020-04-02 16:28:03.857808         619    16      28   GOOG  
80259 2020-04-02 16:28:23.907331         488    16      28   GOOG  
80260 2020-04-02 16:29:37.688654         669    16      29   GOOG  

[80261 rows x 20 columns]

In [7]:
# the first bar is NaN throughout. It's not an error in the candlesticking, but rather it's due to the P3 cleaning which removes all data points between 09:00:00 and 09:01:00 on 2020-04-01
# so apparently Google has no trades on Nasdaq before 1 minute into the open
candles = candleCreateNP_vect_final(cleanedData, step=1, sample=DATA_SAMPLE, numpied=True)
candles

array([[1124.46  , 1124.46  , 1124.2033, 1124.2033],
       [1124.62  , 1125.74  , 1124.51  , 1125.74  ],
       [1125.74  , 1125.74  , 1124.2   , 1124.2   ],
       ...,
       [1119.09  , 1121.53  , 1119.09  , 1121.53  ],
       [1119.09  , 1119.09  , 1119.    , 1119.    ],
       [1119.    , 1119.    , 1119.    , 1119.    ]])

# Load technical features

A library: https://technical-analysis-library-in-python.readthedocs.io/en/latest/

### Features used in the literature:

* Stochastic K - Implemented
* Stochastic D - Implemented
* Slow Stochastic D - Implemented
* Momentum - Same as difference
* ROC - Implemented
* Williams % R - Implemented
* A/D Oscillator
* Disparity 5 - Implemented
* Disparity 10 - Implemented
* Price Oscillator - (detrended) - Implemented
* Commodity Channel Index - Implemented
* RSI - Impliemented

Formulas: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=876544

* Moving Average - Implemented
* Bias
* Exponential Moving Average - Implemented
* Difference - Same af Momentum
* True Range - (Average) - Implemented
* 

Formulas: https://www.sciencedirect.com/science/article/pii/S0957417407001819?via%3Dihub

#### Other Technical Features
* Moving Average Convergence Divergence (MACD) - Implemented

**Non-classical technical features**

* Bid/Ask prices of top of book
* Spread and mid price based on top og book
* Price derivatives

Formulas: https://www.tandfonline.com/doi/full/10.1080/14697688.2015.1032546?instName=UCL+%28University+College+London%29

In [8]:
candles[:5]

array([[1124.46  , 1124.46  , 1124.2033, 1124.2033],
       [1124.62  , 1125.74  , 1124.51  , 1125.74  ],
       [1125.74  , 1125.74  , 1124.2   , 1124.2   ],
       [1124.2   , 1126.94  , 1124.2   , 1124.2   ],
       [1124.2   , 1124.2   , 1124.2   , 1124.2   ]])

In [9]:
FEATURE_LAGS = 2
features = generateFeatures_final(data = candles, 
                                   listOfFeatures = ['pastobs',
                                                      'stok',
#                                                       'stod',
#                                                       'sstod',
#                                                       'wilr',
#                                                       'roc',
#                                                       'rsi',
#                                                       'atr',
#                                                       'cci',
#                                                       'dpo',
#                                                       'sma',
#                                                       'ema',
#                                                       'macd',
#                                                       'dis5',
#                                                       'dis10'
                                                    ], 
                                   feature_lags = FEATURE_LAGS) # 0 for no lags, 1 for 1 lag (returns both raw & first lag)
features[:20] 

open_lag0  high_lag0  low_lag0  close_lag0   stok_lag0  open_lag1  \
0    1125.740    1125.74  1124.200    1124.200         NaN   1124.620   
1    1124.200    1126.94  1124.200    1124.200         NaN   1125.740   
2    1124.200    1124.20  1124.200    1124.200         NaN   1124.200   
3    1124.200    1124.52  1124.200    1124.200         NaN   1124.200   
4    1124.605    1130.00  1124.200    1126.620         NaN   1124.200   
5    1130.000    1130.00  1124.210    1124.210         NaN   1124.605   
6    1130.000    1130.00  1126.100    1130.000         NaN   1130.000   
7    1127.000    1127.00  1125.082    1125.082         NaN   1130.000   
8    1125.790    1125.79  1125.790    1125.790         NaN   1127.000   
9    1125.410    1125.41  1125.410    1125.410         NaN   1125.790   
10   1125.410    1125.41  1125.410    1125.410         NaN   1125.410   
11   1125.410    1125.41  1125.410    1125.410   20.862069   1125.410   
12   1130.000    1130.00  1130.000    1130.000  100.000000   1125.410   
13   1127.750    1127.78  1127.750    1127.780   61.724138   1130.000   
14   1126.010    1130.00  1125.210    1130.000  100.000000   1127.750   
15   1130.000    1130.00  1124.990    1124.990   13.620690   1126.010   
16   1124.990    1125.89  1124.200    1124.200    0.000000   1130.000   
17   1124.200    1125.89  1124.200    1124.990   13.620690   1124.990   
18   1125.250    1125.90  1124.000    1124.000    0.000000   1124.200   
19   1124.200    1126.00  1124.000    1126.000   33.333333   1125.250   

    high_lag1  low_lag1  close_lag1   stok_lag1  open_lag2  high_lag2  \
0     1125.74  1124.510    1125.740         NaN   1124.460    1124.46   
1     1125.74  1124.200    1124.200         NaN   1124.620    1125.74   
2     1126.94  1124.200    1124.200         NaN   1125.740    1125.74   
3     1124.20  1124.200    1124.200         NaN   1124.200    1126.94   
4     1124.52  1124.200    1124.200         NaN   1124.200    1124.20   
5     1130.00  1124.200    1126.620         NaN   1124.200    1124.52   
6     1130.00  1124.210    1124.210         NaN   1124.605    1130.00   
7     1130.00  1126.100    1130.000         NaN   1130.000    1130.00   
8     1127.00  1125.082    1125.082         NaN   1130.000    1130.00   
9     1125.79  1125.790    1125.790         NaN   1127.000    1127.00   
10    1125.41  1125.410    1125.410         NaN   1125.790    1125.79   
11    1125.41  1125.410    1125.410         NaN   1125.410    1125.41   
12    1125.41  1125.410    1125.410   20.862069   1125.410    1125.41   
13    1130.00  1130.000    1130.000  100.000000   1125.410    1125.41   
14    1127.78  1127.750    1127.780   61.724138   1130.000    1130.00   
15    1130.00  1125.210    1130.000  100.000000   1127.750    1127.78   
16    1130.00  1124.990    1124.990   13.620690   1126.010    1130.00   
17    1125.89  1124.200    1124.200    0.000000   1130.000    1130.00   
18    1125.89  1124.200    1124.990   13.620690   1124.990    1125.89   
19    1125.90  1124.000    1124.000    0.000000   1124.200    1125.89   

     low_lag2  close_lag2   stok_lag2  
0   1124.2033   1124.2033         NaN  
1   1124.5100   1125.7400         NaN  
2   1124.2000   1124.2000         NaN  
3   1124.2000   1124.2000         NaN  
4   1124.2000   1124.2000         NaN  
5   1124.2000   1124.2000         NaN  
6   1124.2000   1126.6200         NaN  
7   1124.2100   1124.2100         NaN  
8   1126.1000   1130.0000         NaN  
9   1125.0820   1125.0820         NaN  
10  1125.7900   1125.7900         NaN  
11  1125.4100   1125.4100         NaN  
12  1125.4100   1125.4100         NaN  
13  1125.4100   1125.4100   20.862069  
14  1130.0000   1130.0000  100.000000  
15  1127.7500   1127.7800   61.724138  
16  1125.2100   1130.0000  100.000000  
17  1124.9900   1124.9900   13.620690  
18  1124.2000   1124.2000    0.000000  
19  1124.2000   1124.9900   13.620690

In [10]:
features[-20:]

open_lag0  high_lag0   low_lag0  close_lag0  stok_lag0  open_lag1  \
880  1121.1100  1121.1100  1121.1100   1121.1100  79.357143  1121.1100   
881  1120.8400  1121.1100  1120.8400   1121.1100  85.461538  1121.1100   
882  1121.1100  1121.5300  1121.1100   1121.1100  85.461538  1120.8400   
883  1120.8400  1121.1100  1120.8400   1121.1100  85.461538  1121.1100   
884  1120.8400  1121.5300  1120.8400   1121.5300  88.692308  1120.8400   
885  1122.0550  1122.0550  1122.0550   1122.0550  92.730769  1120.8400   
886  1122.0550  1122.0550  1122.0550   1122.0550  92.730769  1122.0550   
887  1121.1100  1121.1100  1121.1100   1121.1100  16.981132  1122.0550   
888  1121.1100  1121.1100  1121.1100   1121.1100  16.981132  1121.1100   
889  1121.1100  1121.1100  1121.1100   1121.1100  16.981132  1121.1100   
890  1119.4500  1121.5300  1119.0900   1121.5300  73.053892  1121.1100   
891  1121.5300  1121.5300  1121.5300   1121.5300  73.053892  1119.4500   
892  1119.0900  1122.0000  1119.0900   1122.0000  98.145025  1121.5300   
893  1121.5267  1121.5267  1121.5267   1121.5267  82.182125  1119.0900   
894  1119.0900  1119.0900  1119.0900   1119.0900   0.000000  1121.5267   
895  1119.0900  1121.5300  1119.0900   1121.5300  82.293423  1119.0900   
896  1119.0900  1119.0900  1119.0000   1119.0000   0.000000  1119.0900   
897  1119.0000  1119.0000  1119.0000   1119.0000   0.000000  1119.0900   
898        NaN        NaN        NaN         NaN        NaN  1119.0000   
899        NaN        NaN        NaN         NaN        NaN        NaN   

     high_lag1   low_lag1  close_lag1  stok_lag1  open_lag2  high_lag2  \
880  1121.1100  1121.1100   1121.1100  79.357143  1121.1100  1122.4300   
881  1121.1100  1121.1100   1121.1100  79.357143  1121.1100  1121.1100   
882  1121.1100  1120.8400   1121.1100  85.461538  1121.1100  1121.1100   
883  1121.5300  1121.1100   1121.1100  85.461538  1120.8400  1121.1100   
884  1121.1100  1120.8400   1121.1100  85.461538  1121.1100  1121.5300   
885  1121.5300  1120.8400   1121.5300  88.692308  1120.8400  1121.1100   
886  1122.0550  1122.0550   1122.0550  92.730769  1120.8400  1121.5300   
887  1122.0550  1122.0550   1122.0550  92.730769  1122.0550  1122.0550   
888  1121.1100  1121.1100   1121.1100  16.981132  1122.0550  1122.0550   
889  1121.1100  1121.1100   1121.1100  16.981132  1121.1100  1121.1100   
890  1121.1100  1121.1100   1121.1100  16.981132  1121.1100  1121.1100   
891  1121.5300  1119.0900   1121.5300  73.053892  1121.1100  1121.1100   
892  1121.5300  1121.5300   1121.5300  73.053892  1119.4500  1121.5300   
893  1122.0000  1119.0900   1122.0000  98.145025  1121.5300  1121.5300   
894  1121.5267  1121.5267   1121.5267  82.182125  1119.0900  1122.0000   
895  1119.0900  1119.0900   1119.0900   0.000000  1121.5267  1121.5267   
896  1121.5300  1119.0900   1121.5300  82.293423  1119.0900  1119.0900   
897  1119.0900  1119.0000   1119.0000   0.000000  1119.0900  1121.5300   
898  1119.0000  1119.0000   1119.0000   0.000000  1119.0900  1119.0900   
899        NaN        NaN         NaN        NaN  1119.0000  1119.0000   

      low_lag2  close_lag2  stok_lag2  
880  1121.0000   1122.4300  88.785714  
881  1121.1100   1121.1100  79.357143  
882  1121.1100   1121.1100  79.357143  
883  1120.8400   1121.1100  85.461538  
884  1121.1100   1121.1100  85.461538  
885  1120.8400   1121.1100  85.461538  
886  1120.8400   1121.5300  88.692308  
887  1122.0550   1122.0550  92.730769  
888  1122.0550   1122.0550  92.730769  
889  1121.1100   1121.1100  16.981132  
890  1121.1100   1121.1100  16.981132  
891  1121.1100   1121.1100  16.981132  
892  1119.0900   1121.5300  73.053892  
893  1121.5300   1121.5300  73.053892  
894  1119.0900   1122.0000  98.145025  
895  1121.5267   1121.5267  82.182125  
896  1119.0900   1119.0900   0.000000  
897  1119.0900   1121.5300  82.293423  
898  1119.0000   1119.0000   0.000000  
899  1119.0000   1119.0000   0.000000

# Preprocessing of the features 
- Make sure burn-in is removed correctly (dependent on using sample=='full' or sample=='stable')
 * It should be daily burn-in for sample=='stable' and only-once burn-in for sample=='full'
 * We note here that sample=='full' is slightly misleading, as it's not the full data sample but only full market open [9, 16.5]
- Min/max, std, norm, difference-to-close
- Be aware that not all preprocessing approaches make sense for all features (e.g. difference-to-close is only meant for features that describe a price)


In [77]:
# first extract labels
#labels = extract_labels(data = candles, classes = 5, group_style = 'equal')

In [11]:
def extract_labels(data = '', classes = 5, group_style = 'equal'):
    
   # returns = ((data.T[-1][1:]/data.T[-1][0:-1])-1)*100
    returns = ((data[1:, -1] / data[:-1, -1])-1)*100
    
    labels = np.zeros(returns.shape[0])

    if group_style == 'equal':
        thresholdsMin = [np.array_split(np.sort(returns),classes)[i].min() for i in np.arange(classes)]
        thresholdsMax = [np.array_split(np.sort(returns),classes)[i].max() for i in np.arange(classes)]    
    elif group_style != 'equal':
        raise ValueError(f'group_style {group_style} not implemented')
    
    for i in np.arange(classes):
        if i == 0:
            labels[(returns <= thresholdsMax[i])] = i

        elif i == (classes-1):
            labels[(returns >= thresholdsMin[i])] = i

        else:
            labels[(returns >= thresholdsMin[i]) & (returns<=thresholdsMax[i])] = i  
            
    return labels, returns, [thresholdsMin, thresholdsMax]

group_style = 'equal'
classes = 5

#returns = ((candles.T[-1][1:]/candles.T[-1][0:-1])-1)*100
returns = ((candles[1:, -1] / candles[:-1, -1])-1)*100

labels = np.zeros(returns.shape[0])

if group_style == 'equal':
    thresholdsMin = [np.array_split(np.sort(returns),classes)[i].min() for i in np.arange(classes)]
    thresholdsMax = [np.array_split(np.sort(returns),classes)[i].max() for i in np.arange(classes)]    
elif group_style != 'equal':
    raise ValueError(f'group_style {group_style} not implemented')

for i in np.arange(classes):
    if i == 0:
        labels[(returns <= thresholdsMax[i])] = i

    elif i == (classes-1):
        labels[(returns >= thresholdsMin[i])] = i

    else:
        labels[(returns >= thresholdsMin[i]) & (returns<=thresholdsMax[i])] = i  

#return labels



In [12]:
candles

array([[1124.46  , 1124.46  , 1124.2033, 1124.2033],
       [1124.62  , 1125.74  , 1124.51  , 1125.74  ],
       [1125.74  , 1125.74  , 1124.2   , 1124.2   ],
       ...,
       [1119.09  , 1121.53  , 1119.09  , 1121.53  ],
       [1119.09  , 1119.09  , 1119.    , 1119.    ],
       [1119.    , 1119.    , 1119.    , 1119.    ]])

In [13]:
thresholdsMin, thresholdsMax

([-0.5728085977076858,
  -0.10187603155042968,
  -0.023824936167138322,
  0.02411821512358081,
  0.09681449094316452],
 [-0.1020152485950665,
  -0.023979324493550447,
  0.0237205148947206,
  0.09677288300853348,
  0.6751130411425166])

In [14]:
returns

array([ 1.36692358e-01, -1.36798906e-01,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.15264188e-01, -2.13914186e-01,  5.15028331e-01,
       -4.35221239e-01,  6.29287465e-02, -3.37540749e-02,  0.00000000e+00,
        0.00000000e+00,  4.07851361e-01, -1.96460177e-01,  1.96846903e-01,
       -4.43362832e-01, -7.02228464e-02,  7.02721936e-02, -8.80007822e-02,
        1.77935943e-01, -1.77619893e-02, -1.59886303e-01,  3.82562278e-02,
        3.82415980e-02,  1.01345945e-01, -2.66429840e-03, -2.39793245e-02,
       -3.05587634e-01,  3.26127635e-01, -1.63377505e-01,  3.30003056e-01,
       -4.47654262e-01, -9.23097696e-02, -4.32823247e-01,  6.75113041e-01,
        3.04449524e-01, -1.00477632e-01, -2.32541627e-01,  4.67590698e-02,
        1.04313980e-01,  2.67641725e-02, -7.90277605e-02, -1.03993165e-01,
       -1.67562278e-01, -2.90219394e-01,  5.00509447e-02,  1.78663951e-03,
        5.00250125e-02,  1.17857143e-01, -6.50750901e-02, -1.80253211e-01,
        1.92915886e-01, -

In [15]:
labels

array([4., 0., 2., 2., 2., 4., 0., 4., 0., 3., 1., 2., 2., 4., 0., 4., 0.,
       1., 3., 1., 4., 2., 0., 3., 3., 4., 2., 1., 0., 4., 0., 4., 0., 1.,
       0., 4., 4., 1., 0., 3., 4., 3., 1., 0., 0., 0., 3., 2., 3., 4., 1.,
       0., 4., 0., 3., 3., 1., 0., 3., 3., 0., 3., 3., 1., 4., 4., 4., 4.,
       1., 2., 3., 2., 4., 4., 2., 2., 0., 3., 0., 3., 2., 1., 1., 0., 2.,
       2., 3., 0., 4., 2., 4., 3., 3., 2., 3., 2., 2., 3., 1., 1., 1., 4.,
       1., 1., 4., 1., 1., 0., 3., 1., 1., 3., 3., 0., 1., 2., 4., 1., 4.,
       1., 2., 1., 4., 3., 3., 2., 1., 2., 2., 1., 3., 0., 0., 4., 0., 3.,
       4., 3., 2., 3., 0., 1., 0., 1., 2., 1., 3., 1., 1., 1., 3., 3., 1.,
       3., 3., 0., 4., 1., 0., 1., 1., 1., 3., 4., 1., 0., 2., 2., 2., 4.,
       3., 1., 3., 2., 3., 1., 4., 1., 0., 2., 0., 1., 3., 2., 4., 1., 0.,
       1., 2., 4., 2., 0., 4., 4., 1., 1., 1., 2., 1., 3., 3., 1., 3., 1.,
       3., 0., 1., 3., 2., 2., 2., 3., 0., 3., 1., 1., 2., 0., 0., 2., 1.,
       0., 3., 4., 2., 1.

In [121]:
SAFE_BURN_IN = False # True for restarting burn-in each day, False for continuing from yesterday's close (DATA_SAMPLE = 'stable' requires SAFE_BURN_IN = True )

if (DATA_SAMPLE == 'stable') & (not SAFE_BURN_IN):
    raise ValueError(f'DATA_SAMPLE = "{DATA_SAMPLE}" & SAFE_BURN_IN = "{SAFE_BURN_IN}" not allowed. Burn-in needs a restart with DATA_SAMPLE = "{DATA_SAMPLE}" as we skip 30 minutes')

# # postponing this for later
# to do: allow burn-in to happen every day (we probably need to extract the MultiIndex from candles to do this in a nice vectorized way)
    # 
# if SAFE_BURN_IN:
    
#     # for each day ...
    
#     # get first index that has no NaNs (the sum checks for True across columns, we look for sum == 0 and where that is first True)
#     burned_in_idx = np.where((np.sum(np.isnan(features.values), axis=1) == 0) == True)[0][0]
    
#     # slice away the observations used for burn-in
#     burned_in_features = features.iloc[burned_in_idx:, :] # features[burned_in_idx:] latter is sligthly faster but maybe not as precise
    
#     # check if there are remaining NaNs are burn-in (means error)
#     remaining_nans = np.where(np.isnan(burned_in_features.values))[0].size
#     if remaining_nans > 0:
#         raise ValueError('Had NaN in burned_in_features after burn-in')
        
prediction_horizon = 1
    
if not SAFE_BURN_IN:
    assert DATA_SAMPLE == 'full'
    # we assume data_sample is full and that we can continue features from yesterday's values.
    # that we have a single burn-in at the beginning and that's it
    
    # get first index that has no NaNs (the sum checks for True across columns, we look for sum == 0 and where that is first True)
    burned_in_idx = np.where((np.sum(np.isnan(features.values), axis=1) == 0) == True)[0][0]
    
    # calculate end-point cut-off to match with labels
    end_point_cut = max(prediction_horizon, FEATURE_LAGS) + 1 #prediction_horizon + (FEATURE_LAGS - 2)
    
    # slice away the observations used for burn-in (taking off 1 at the end to match with labels [slice off "prediction_horizon"])
    burned_in_features = features.iloc[burned_in_idx : -end_point_cut, :].reset_index(drop=True) # features[burned_in_idx:] latter is sligthly faster but maybe not as precise
    
    # slice away the burned-in indices from labels
    #labels, _, _ = extract_labels(data = candles[burned_in_idx:, :], classes = 5, group_style = 'equal')
    labels, returns, thresholds = extract_labels(data = candles[burned_in_idx + FEATURE_LAGS : , :], classes = 5, group_style = 'equal')
    
    # check if there are remaining NaNs are burn-in (means error)
    remaining_nans = np.where(np.isnan(burned_in_features.values))[0].size
    if remaining_nans > 0:
        raise ValueError('Had NaN in burned_in_features after burn-in')    

In [122]:
burned_in_features

open_lag0  high_lag0   low_lag0  close_lag0   stok_lag0  open_lag1  \
0    1127.7500  1127.7800  1127.7500   1127.7800   61.724138  1130.0000   
1    1126.0100  1130.0000  1125.2100   1130.0000  100.000000  1127.7500   
2    1130.0000  1130.0000  1124.9900   1124.9900   13.620690  1126.0100   
3    1124.9900  1125.8900  1124.2000   1124.2000    0.000000  1130.0000   
4    1124.2000  1125.8900  1124.2000   1124.9900   13.620690  1124.9900   
5    1125.2500  1125.9000  1124.0000   1124.0000    0.000000  1124.2000   
6    1124.2000  1126.0000  1124.0000   1126.0000   33.333333  1125.2500   
7    1125.0000  1125.8000  1124.2000   1125.8000   30.000000  1124.2000   
8    1125.7000  1125.7900  1124.0000   1124.0000    0.000000  1125.0000   
9    1124.0000  1124.4300  1124.0000   1124.4300    7.166667  1125.7000   
10   1124.0000  1124.8600  1124.0000   1124.8600   14.333333  1124.0000   
11   1124.3700  1126.0000  1124.3700   1126.0000   33.333333  1124.0000   
12   1128.0000  1128.0000  1124.9800   1125.9700   32.833333  1124.3700   
13   1124.8600  1125.7000  1123.0000   1125.7000   38.571429  1128.0000   
14   1123.7000  1123.7000  1122.2600   1122.2600    0.000000  1124.8600   
15   1122.2600  1127.8800  1119.5100   1125.9200   61.105815  1123.7000   
16   1127.0000  1128.1099  1120.0000   1124.0805   53.145967  1122.2600   
17   1127.1900  1128.0800  1123.0000   1127.7900   96.280189  1127.0000   
18   1126.9800  1126.9800  1122.0000   1122.7414   37.574856  1127.1900   
19   1123.6700  1123.7600  1120.0000   1121.7050   25.523553  1126.9800   
20   1121.2100  1121.8500  1114.5300   1116.8500   17.084073  1123.6700   
21   1117.0400  1124.4000  1116.2000   1124.3900   72.607309  1121.2100   
22   1124.8000  1128.2100  1124.7550   1127.8132   97.099415  1117.0400   
23   1127.6300  1128.7000  1125.1800   1126.6800   85.744531  1124.8000   
24   1127.3780  1127.6299  1123.6950   1124.0600   67.254764  1127.6300   
25   1125.1840  1125.8990  1123.0000   1124.5856   70.964008  1127.3780   
26   1124.1200  1126.4400  1123.6700   1125.7587   79.242766  1125.1840   
27   1125.6600  1127.6300  1124.7000   1126.0600   81.369090  1124.1200   
28   1125.6500  1128.4200  1125.1500   1125.1701   75.088920  1125.6600   
29   1125.8300  1127.2300  1124.0000   1124.0000   66.831334  1125.6500   
..         ...        ...        ...         ...         ...        ...   
854  1122.7250  1124.0000  1119.2100   1121.7400   90.668869  1122.5800   
855  1120.8400  1120.8400  1116.0300   1120.8400   86.952931  1122.7250   
856  1115.6800  1119.0000  1115.6800   1119.0000   79.355904  1120.8400   
857  1120.0000  1120.9900  1120.0000   1120.9900   87.572254  1115.6800   
858  1120.4600  1122.0000  1120.4400   1120.4400   85.301404  1120.0000   
859  1120.8400  1121.0200  1120.8400   1120.8500   86.994220  1120.4600   
860  1120.8400  1123.0000  1110.0000   1123.0000   95.871181  1120.8400   
861  1120.8720  1120.8720  1120.8400   1120.8507   86.997110  1120.8400   
862  1120.8507  1120.8507  1120.8507   1120.8507   77.505000  1120.8720   
863  1122.4200  1122.4200  1120.8400   1120.8400   77.428571  1120.8507   
864  1120.8400  1120.8400  1120.8400   1120.8400   77.428571  1122.4200   
865  1121.1100  1122.4300  1121.0000   1122.4300   88.785714  1120.8400   
866  1121.1100  1121.1100  1121.1100   1121.1100   79.357143  1121.1100   
867  1121.1100  1121.1100  1121.1100   1121.1100   79.357143  1121.1100   
868  1120.8400  1121.1100  1120.8400   1121.1100   85.461538  1121.1100   
869  1121.1100  1121.5300  1121.1100   1121.1100   85.461538  1120.8400   
870  1120.8400  1121.1100  1120.8400   1121.1100   85.461538  1121.1100   
871  1120.8400  1121.5300  1120.8400   1121.5300   88.692308  1120.8400   
872  1122.0550  1122.0550  1122.0550   1122.0550   92.730769  1120.8400   
873  1122.0550  1122.0550  1122.0550   1122.0550   92.730769  1122.0550   
874  1121.1100  1121.1100  1121.1100   1121.1100   16.981132  1122.0550   
875  1121.1100  1121.1100  112

In [123]:
labels, returns, thresholds

(array([4., 0., 1., 3., 1., 4., 2., 0., 3., 3., 4., 2., 2., 0., 4., 0., 4.,
        0., 1., 0., 4., 4., 1., 0., 3., 4., 3., 1., 0., 0., 0., 3., 2., 3.,
        4., 1., 0., 4., 0., 3., 3., 1., 0., 3., 3., 0., 3., 3., 1., 4., 4.,
        4., 4., 1., 2., 3., 2., 4., 4., 2., 2., 0., 3., 0., 3., 2., 1., 1.,
        0., 2., 2., 3., 0., 4., 2., 4., 3., 3., 2., 3., 2., 2., 3., 1., 1.,
        1., 4., 1., 1., 4., 1., 1., 0., 3., 1., 1., 3., 3., 0., 0., 2., 4.,
        1., 4., 1., 2., 1., 4., 3., 3., 2., 1., 2., 2., 1., 3., 0., 0., 4.,
        0., 3., 4., 3., 2., 3., 0., 1., 0., 1., 2., 1., 3., 1., 1., 1., 3.,
        3., 1., 3., 3., 0., 4., 1., 0., 1., 1., 1., 3., 4., 1., 0., 2., 2.,
        2., 4., 3., 1., 3., 2., 3., 1., 4., 1., 0., 2., 0., 1., 3., 2., 4.,
        1., 0., 1., 2., 4., 2., 0., 4., 4., 1., 1., 1., 2., 1., 3., 3., 1.,
        3., 1., 3., 0., 1., 3., 2., 2., 2., 3., 0., 3., 1., 1., 2., 0., 0.,
        2., 1., 0., 3., 4., 2., 1., 4., 0., 3., 3., 4., 3., 1., 4., 2., 1.,
        1., 

In [124]:
labels.shape, returns.shape, features.shape, burned_in_features.shape

((884,), (884,), (900, 15), (884, 15))

In [11]:
features[0:20]

open_lag0  high_lag0  low_lag0  close_lag0   stok_lag0  open_lag1  \
0    1125.740    1125.74  1124.200    1124.200         NaN   1124.620   
1    1124.200    1126.94  1124.200    1124.200         NaN   1125.740   
2    1124.200    1124.20  1124.200    1124.200         NaN   1124.200   
3    1124.200    1124.52  1124.200    1124.200         NaN   1124.200   
4    1124.605    1130.00  1124.200    1126.620         NaN   1124.200   
5    1130.000    1130.00  1124.210    1124.210         NaN   1124.605   
6    1130.000    1130.00  1126.100    1130.000         NaN   1130.000   
7    1127.000    1127.00  1125.082    1125.082         NaN   1130.000   
8    1125.790    1125.79  1125.790    1125.790         NaN   1127.000   
9    1125.410    1125.41  1125.410    1125.410         NaN   1125.790   
10   1125.410    1125.41  1125.410    1125.410         NaN   1125.410   
11   1125.410    1125.41  1125.410    1125.410   20.862069   1125.410   
12   1130.000    1130.00  1130.000    1130.000  100.000000   1125.410   
13   1127.750    1127.78  1127.750    1127.780   61.724138   1130.000   
14   1126.010    1130.00  1125.210    1130.000  100.000000   1127.750   
15   1130.000    1130.00  1124.990    1124.990   13.620690   1126.010   
16   1124.990    1125.89  1124.200    1124.200    0.000000   1130.000   
17   1124.200    1125.89  1124.200    1124.990   13.620690   1124.990   
18   1125.250    1125.90  1124.000    1124.000    0.000000   1124.200   
19   1124.200    1126.00  1124.000    1126.000   33.333333   1125.250   

    high_lag1  low_lag1  close_lag1   stok_lag1  open_lag2  high_lag2  \
0     1125.74  1124.510    1125.740         NaN   1124.460    1124.46   
1     1125.74  1124.200    1124.200         NaN   1124.620    1125.74   
2     1126.94  1124.200    1124.200         NaN   1125.740    1125.74   
3     1124.20  1124.200    1124.200         NaN   1124.200    1126.94   
4     1124.52  1124.200    1124.200         NaN   1124.200    1124.20   
5     1130.00  1124.200    1126.620         NaN   1124.200    1124.52   
6     1130.00  1124.210    1124.210         NaN   1124.605    1130.00   
7     1130.00  1126.100    1130.000         NaN   1130.000    1130.00   
8     1127.00  1125.082    1125.082         NaN   1130.000    1130.00   
9     1125.79  1125.790    1125.790         NaN   1127.000    1127.00   
10    1125.41  1125.410    1125.410         NaN   1125.790    1125.79   
11    1125.41  1125.410    1125.410         NaN   1125.410    1125.41   
12    1125.41  1125.410    1125.410   20.862069   1125.410    1125.41   
13    1130.00  1130.000    1130.000  100.000000   1125.410    1125.41   
14    1127.78  1127.750    1127.780   61.724138   1130.000    1130.00   
15    1130.00  1125.210    1130.000  100.000000   1127.750    1127.78   
16    1130.00  1124.990    1124.990   13.620690   1126.010    1130.00   
17    1125.89  1124.200    1124.200    0.000000   1130.000    1130.00   
18    1125.89  1124.200    1124.990   13.620690   1124.990    1125.89   
19    1125.90  1124.000    1124.000    0.000000   1124.200    1125.89   

     low_lag2  close_lag2   stok_lag2  
0   1124.2033   1124.2033         NaN  
1   1124.5100   1125.7400         NaN  
2   1124.2000   1124.2000         NaN  
3   1124.2000   1124.2000         NaN  
4   1124.2000   1124.2000         NaN  
5   1124.2000   1124.2000         NaN  
6   1124.2000   1126.6200         NaN  
7   1124.2100   1124.2100         NaN  
8   1126.1000   1130.0000         NaN  
9   1125.0820   1125.0820         NaN  
10  1125.7900   1125.7900         NaN  
11  1125.4100   1125.4100         NaN  
12  1125.4100   1125.4100         NaN  
13  1125.4100   1125.4100   20.862069  
14  1130.0000   1130.0000  100.000000  
15  1127.7500   1127.7800   61.724138  
16  1125.2100   1130.0000  100.000000  
17  1124.9900   1124.9900   13.620690  
18  1124.2000   1124.2000    0.000000  
19  1124.2000   1124.9900   13.620690

In [12]:
candles

array([[1124.46  , 1124.46  , 1124.2033, 1124.2033],
       [1124.62  , 1125.74  , 1124.51  , 1125.74  ],
       [1125.74  , 1125.74  , 1124.2   , 1124.2   ],
       ...,
       [1119.09  , 1121.53  , 1119.09  , 1121.53  ],
       [1119.09  , 1119.09  , 1119.    , 1119.    ],
       [1119.    , 1119.    , 1119.    , 1119.    ]])

In [126]:
burned_in_features[:3]

open_lag0  high_lag0  low_lag0  close_lag0   stok_lag0  open_lag1  \
0    1127.75    1127.78   1127.75     1127.78   61.724138    1130.00   
1    1126.01    1130.00   1125.21     1130.00  100.000000    1127.75   
2    1130.00    1130.00   1124.99     1124.99   13.620690    1126.01   

   high_lag1  low_lag1  close_lag1   stok_lag1  open_lag2  high_lag2  \
0    1130.00   1130.00     1130.00  100.000000    1125.41    1125.41   
1    1127.78   1127.75     1127.78   61.724138    1130.00    1130.00   
2    1130.00   1125.21     1130.00  100.000000    1127.75    1127.78   

   low_lag2  close_lag2   stok_lag2  
0   1125.41     1125.41   20.862069  
1   1130.00     1130.00  100.000000  
2   1127.75     1127.78   61.724138

In [127]:
candles[burned_in_idx + FEATURE_LAGS: -(end_point_cut-1), :][:3]

array([[1127.75, 1127.78, 1127.75, 1127.78],
       [1126.01, 1130.  , 1125.21, 1130.  ],
       [1130.  , 1130.  , 1124.99, 1124.99]])

In [128]:
 labels[:3], returns[:3]

(array([4., 0., 1.]), array([ 0.1968469 , -0.44336283, -0.07022285]))

In [129]:
# So the increase of 0.40785136 % matches index 13 to 14 (0 to 1 of burned_in_features vector), so this is fine (0.40785136 % should be the return used in label for index 13)
# Means that most likely only the end-point has to be removed, lets check:

In [130]:
# example of X, y:
burned_in_features[:1], labels[:1], returns[:1]

(   open_lag0  high_lag0  low_lag0  close_lag0  stok_lag0  open_lag1  \
 0    1127.75    1127.78   1127.75     1127.78  61.724138     1130.0   
 
    high_lag1  low_lag1  close_lag1  stok_lag1  open_lag2  high_lag2  low_lag2  \
 0     1130.0    1130.0      1130.0      100.0    1125.41    1125.41   1125.41   
 
    close_lag2  stok_lag2  
 0     1125.41  20.862069  , array([4.]), array([0.1968469]))

In [131]:
# Check the end-point
features[-6:]

open_lag0  high_lag0  low_lag0  close_lag0  stok_lag0  open_lag1  \
894    1119.09    1119.09   1119.09     1119.09   0.000000  1121.5267   
895    1119.09    1121.53   1119.09     1121.53  82.293423  1119.0900   
896    1119.09    1119.09   1119.00     1119.00   0.000000  1119.0900   
897    1119.00    1119.00   1119.00     1119.00   0.000000  1119.0900   
898        NaN        NaN       NaN         NaN        NaN  1119.0000   
899        NaN        NaN       NaN         NaN        NaN        NaN   

     high_lag1   low_lag1  close_lag1  stok_lag1  open_lag2  high_lag2  \
894  1121.5267  1121.5267   1121.5267  82.182125  1119.0900  1122.0000   
895  1119.0900  1119.0900   1119.0900   0.000000  1121.5267  1121.5267   
896  1121.5300  1119.0900   1121.5300  82.293423  1119.0900  1119.0900   
897  1119.0900  1119.0000   1119.0000   0.000000  1119.0900  1121.5300   
898  1119.0000  1119.0000   1119.0000   0.000000  1119.0900  1119.0900   
899        NaN        NaN         NaN        NaN  1119.0000  1119.0000   

      low_lag2  close_lag2  stok_lag2  
894  1119.0900   1122.0000  98.145025  
895  1121.5267   1121.5267  82.182125  
896  1119.0900   1119.0900   0.000000  
897  1119.0900   1121.5300  82.293423  
898  1119.0000   1119.0000   0.000000  
899  1119.0000   1119.0000   0.000000

In [132]:
burned_in_features[-6:]

open_lag0  high_lag0   low_lag0  close_lag0  stok_lag0  open_lag1  \
878  1121.5300  1121.5300  1121.5300   1121.5300  73.053892  1119.4500   
879  1119.0900  1122.0000  1119.0900   1122.0000  98.145025  1121.5300   
880  1121.5267  1121.5267  1121.5267   1121.5267  82.182125  1119.0900   
881  1119.0900  1119.0900  1119.0900   1119.0900   0.000000  1121.5267   
882  1119.0900  1121.5300  1119.0900   1121.5300  82.293423  1119.0900   
883  1119.0900  1119.0900  1119.0000   1119.0000   0.000000  1119.0900   

     high_lag1   low_lag1  close_lag1  stok_lag1  open_lag2  high_lag2  \
878  1121.5300  1119.0900   1121.5300  73.053892  1121.1100  1121.1100   
879  1121.5300  1121.5300   1121.5300  73.053892  1119.4500  1121.5300   
880  1122.0000  1119.0900   1122.0000  98.145025  1121.5300  1121.5300   
881  1121.5267  1121.5267   1121.5267  82.182125  1119.0900  1122.0000   
882  1119.0900  1119.0900   1119.0900   0.000000  1121.5267  1121.5267   
883  1121.5300  1119.0900   1121.5300  82.293423  1119.0900  1119.0900   

      low_lag2  close_lag2  stok_lag2  
878  1121.1100   1121.1100  16.981132  
879  1119.0900   1121.5300  73.053892  
880  1121.5300   1121.5300  73.053892  
881  1119.0900   1122.0000  98.145025  
882  1121.5267   1121.5267  82.182125  
883  1119.0900   1119.0900   0.000000

In [133]:
 labels[-6:], returns[-6:]

(array([3., 1., 0., 4., 0., 2.]),
 array([ 0.04190704, -0.0421836 , -0.21726634,  0.2180343 , -0.22558469,
         0.        ]))

In [110]:
# The decrease of -0.22558469 % matches index 895 to 896 (882 to 883 of burned_in_features vector)
# Means that the feature matrix has one row too many as expected (index 899 has no subsequent close price) so no label
# we solve this by slicing off 1 row at the end.
# note that we should actually, in the general case, slice off "prediction_horizon" (equal to 1 here) at the end of the feature matrix

In [134]:
# example of X, y:
burned_in_features[-2:], labels[-2:], returns[-2:]

(     open_lag0  high_lag0  low_lag0  close_lag0  stok_lag0  open_lag1  \
 882    1119.09    1121.53   1119.09     1121.53  82.293423    1119.09   
 883    1119.09    1119.09   1119.00     1119.00   0.000000    1119.09   
 
      high_lag1  low_lag1  close_lag1  stok_lag1  open_lag2  high_lag2  \
 882    1119.09   1119.09     1119.09   0.000000  1121.5267  1121.5267   
 883    1121.53   1119.09     1121.53  82.293423  1119.0900  1119.0900   
 
       low_lag2  close_lag2  stok_lag2  
 882  1121.5267   1121.5267  82.182125  
 883  1119.0900   1119.0900   0.000000  ,
 array([0., 2.]),
 array([-0.22558469,  0.        ]))

# Drafts and ad hoc timings

In [58]:
#features.isnull().sum(axis=1) == 0
%timeit np.where(np.isnan(features.values))[0][-1] # 5 times faster than with .values
%timeit np.where(np.isnan(features))[0][-1]
%timeit np.where(features.isnull())[0][-1]
#np.where(np.isnan(x))

47.2 µs ± 4.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
234 µs ± 26.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
239 µs ± 27.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [60]:
np.where(np.isnan(features.values))

(array([ 0,  0,  0,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
        13], dtype=int64),
 array([0, 1, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64))

In [66]:
%timeit np.where((features.isnull().sum(axis=1) == 0)==True)[0][0]
%timeit np.where((np.sum(np.isnan(features.values), axis=1) == 0) == True)[0][0]

1.05 ms ± 8.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
52.3 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [67]:
np.where((np.sum(np.isnan(features.values), axis=1) == 0)==True)[0][0]

14

In [68]:
burned_in_idx = np.where((np.sum(np.isnan(features.values), axis=1) == 0) == True)[0][0]

In [71]:
%timeit features[burned_in_idx:]
%timeit features.iloc[burned_in_idx:, :]

114 µs ± 5.24 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
143 µs ± 581 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [73]:
features.iloc[burned_in_idx:, :][:10]

open     high      low    close        stok
14  1125.79  1125.79  1125.79  1125.79   51.405622
15  1127.75  1127.78  1127.75  1127.78  100.000000
16  1126.01  1126.01  1125.21  1125.21    0.000000
17  1126.00  1127.00  1126.00  1127.00   69.649805
18  1124.99  1125.89  1124.99  1125.89   32.258065
19  1125.89  1125.89  1124.99  1124.99    0.000000
20  1125.90  1125.90  1124.00  1124.00    0.000000
21  1124.00  1124.00  1124.00  1124.00    0.000000
22  1124.20  1124.20  1124.20  1124.20    5.291005
23  1125.70  1125.79  1124.00  1124.00    0.000000

In [84]:
# Make sure there are no NaNs (this would be mean holes in candlesticks and something else wrong)
np.where(np.isnan(features.iloc[burned_in_idx:, :].values))[0].size

0