In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import os
import time
import h5py
import copy
import datetime
import ta
# Do you wanna see?
verbose = True

from utils.data_extraction import load_data
from utils.data_cleaning import HFDataCleaning

### Load data etc

In [2]:
# print(os.listdir())
path = 'T:/taqhdf5'  #'a:/taqhdf5'
# allFiles = os.listdir(path)
# print(len(allFiles), allFiles[:5], allFiles[-5:])
# print(allFiles[-10:])

dates = np.array(['2020040' + str(i) if i < 10 else '202004' + str(i) for i in np.arange(1,32)]).astype(int)
#dates = np.array(['20200401']).astype(int)

# Provide a list of tickers of interest
tickers = ['GOOG']#'MSFT'

# Do we need data on trades, quotes or both?
dataNeeded = 'trades' # 'trades', 'quotes' or 'both'

# run load_data()
if dataNeeded == 'trades':
    tradeData = load_data(dates, tickers, dataNeeded, path, verbose)
elif dataNeeded == 'quotes':
    quoteData = load_data(dates, tickers, dataNeeded, path, verbose)
elif dataNeeded == 'both':
    tradeData, quoteData = load_data(dates, tickers, dataNeeded, path, verbose)

['.git', '.gitignore', '.ipynb_checkpoints', 'CrunchTAQ.ipynb', 'hello.py', 'README.md', 'Speciale to-do.docx', 'Speciale to-do.txt', 'test', 'test_and_compare_candlesticks.ipynb', 'utils']


FileNotFoundError: [WinError 3] Den angivne sti blev ikke fundet: 'T:/taqhdf5'

In [5]:
cleanedData = HFDataCleaning(['P1','p2','t1','p3'],tradeData,'trade',['q'])

In [6]:
step = 10 # in minutes

aggregateMinute = np.arange(0,60,step)
aggregateHour = np.arange(9,16,1)
aggregateDate = np.arange(len(cleanedData.Date.unique()))

remove = 30//step

# candle = np.zeros(((len(aggregateDate)*len(aggregateMinute)*len(aggregateHour)),4))
candleNP = np.zeros((((len(aggregateDate)*len(aggregateMinute)*len(aggregateHour))-remove*len(aggregateDate)),4))

In [7]:
numpiedData = cleanedData[['Date','Hour','Minute']].to_numpy()
numpiedData = numpiedData.T
numpiedPrice = cleanedData['price'].to_numpy()

### Original

In [8]:


def candleCreateNP():
    ii = 0
    for l in cleanedData.Date.unique():
        for i in aggregateHour:
            for j in aggregateMinute:
                if (i == 9) & (j <30):
                    continue
                
                p1 = numpiedPrice[((numpiedData[0]==l)&\
                                     (numpiedData[1]==i)&\
                                     (numpiedData[2]>=j))&((numpiedData[0]==l)&\
                                                           (numpiedData[1]==i)&\
                                                           (numpiedData[2]<j+step))]
                if len(p1) > 0:
                    candleNP[ii] = np.array([p1[0],p1.max(),p1.min(),p1[-1]])
                else:
                    # if no new prices in the interval considered, use the previous pne
                    candleNP[ii] = candleNP[ii-1]
                ii += 1
                
    return candleNP

In [9]:
# Aggregate data in candle sticks
candleNP = candleCreateNP()

candleNP.shape

(39, 4)

In [10]:
candleNP[:5], candleNP[-5:]

(array([[1122.26, 1128.7 , 1114.79, 1124.52],
        [1124.72, 1127.85, 1118.26, 1120.29],
        [1120.13, 1121.68, 1115.18, 1115.55],
        [1115.35, 1126.  , 1114.3 , 1124.3 ],
        [1124.33, 1129.31, 1123.  , 1124.66]]),
 array([[1105.4 , 1105.71, 1101.8 , 1104.  ],
        [1104.05, 1104.05, 1100.36, 1100.69],
        [1100.76, 1101.28, 1097.44, 1097.88],
        [1097.5 , 1110.68, 1097.21, 1106.87],
        [1106.62, 1110.97, 1102.43, 1105.62]]))

### Attempt to vectorize

In [11]:
cleanedData['hour_min_col'] = cleanedData['Hour'] + cleanedData['Minute']/60
cleanedData.head()

utcsec ex  cond  volume    price TradeStopStockIndicator corr  \
0  34200012706854  Q  @ TI      83  1122.26                           00   
1  34200012711048  Q  @ TI      17  1122.26                           00   
2  34200012771200  Q  @ TI      83  1122.26                           00   
3  34200012827903  Q  @ TI      83  1122.26                           00   
4  34200013120215  Q  @ TI      20  1122.08                           00   

   TradeSequenceNumber TradeID SourceOfTrade  ... ParticipantTime  TRFTime  \
0                36579     447             N  ...  34200012683939       99   
1                36580     448             N  ...  34200012683939       99   
2                36583     449             N  ...  34200012747399       99   
3                36584     450             N  ...  34200012803083       99   
4                36589     451             N  ...  34200013098975       99   

   TTE      Date                  Timestamp TSRemainder Hour  Minute  Ticker  \
0    0  20200401 2020-04-01 09:30:00.012706         854    9      30    GOOG   
1    0  20200401 2020-04-01 09:30:00.012711         048    9      30    GOOG   
2    0  20200401 2020-04-01 09:30:00.012771         200    9      30    GOOG   
3    0  20200401 2020-04-01 09:30:00.012827         903    9      30    GOOG   
4    0  20200401 2020-04-01 09:30:00.013120         215    9      30    GOOG   

  hour_min_col  
0          9.5  
1          9.5  
2          9.5  
3          9.5  
4          9.5  

[5 rows x 21 columns]

In [12]:
cleanedData['hour_min_col'].min(), cleanedData['hour_min_col'].max()

(9.5, 15.983333333333333)

In [13]:
time_bins = np.arange(9.5,16+step/60,step/60)
time_bins

array([ 9.5       ,  9.66666667,  9.83333333, 10.        , 10.16666667,
       10.33333333, 10.5       , 10.66666667, 10.83333333, 11.        ,
       11.16666667, 11.33333333, 11.5       , 11.66666667, 11.83333333,
       12.        , 12.16666667, 12.33333333, 12.5       , 12.66666667,
       12.83333333, 13.        , 13.16666667, 13.33333333, 13.5       ,
       13.66666667, 13.83333333, 14.        , 14.16666667, 14.33333333,
       14.5       , 14.66666667, 14.83333333, 15.        , 15.16666667,
       15.33333333, 15.5       , 15.66666667, 15.83333333, 16.        ,
       16.16666667])

In [14]:
cleanedData['time_group'] = pd.cut(cleanedData['hour_min_col'], bins=time_bins, right=False, labels=False) #0#+1
cleanedData

utcsec ex  cond  volume    price TradeStopStockIndicator corr  \
0      34200012706854  Q  @ TI      83  1122.26                           00   
1      34200012711048  Q  @ TI      17  1122.26                           00   
2      34200012771200  Q  @ TI      83  1122.26                           00   
3      34200012827903  Q  @ TI      83  1122.26                           00   
4      34200013120215  Q  @ TI      20  1122.08                           00   
5      34200134121465  Q  @ TI       1  1122.25                           00   
6      34200137711405  Q  @ TI       1  1121.00                           00   
7      34200194838863  Q  @FTI      38  1122.26                           00   
8      34200194842233  Q  @FTI       1  1122.26                           00   
9      34200194877651  Q  @FTI      15  1124.00                           00   
10     34200194907455  Q  @FTI       6  1124.00                           00   
11     34200195373681  Q  @FTI      15  1124.67                           00   
12     34200466211245  Q  @FTI       5  1121.90                           00   
13     34200720953824  Q  @ TI       1  1121.01                           00   
14     34200720957975  Q  @ TI       4  1121.00                           00   
15     34200724419189  Q  @ TI       1  1121.01                           00   
16     34200866682183  Q  @O X   42862  1121.18                           00   
17     34200866857294  Q  @  Q   42862  1121.18                           00   
18     34200867116388  Q  @F I       3  1121.89                           00   
19     34200879874870  Q  @  I      16  1122.21                           00   
20     34200976326240  Q  @  I      15  1121.20                           00   
21     34200976612907  Q  @  I       3  1121.20                           00   
22     34201012499891  Q  @  I      20  1121.20                           00   
23     34201012502250  Q  @  I       5  1121.20                           00   
24     34201025400251  Q  @  I      10  1121.20                           00   
25     34201025403833  Q  @  I      13  1121.20                           00   
26     34201066140964  Q  @F I       2  1121.20                           00   
27     34201066144236  Q  @F I      73  1121.19                           00   
28     34201100745935  Q  @F I       1  1121.23                           00   
29     34201190580017  Q  @  I      23  1122.11                           00   
...               ... ..   ...     ...      ...                     ...  ...   
23332  57599397305236  Q  @        100  1106.00                           00   
23333  57599403461670  Q  @F I      90  1106.09                           00   
23334  57599403464862  Q  @F I      10  1106.01                           00   
23335  57599403474319  Q  @F       100  1106.00                           00   
23336  57599422592191  Q  @F I      14  1106.00                           00   
23337  57599423030674  Q  @F I      86  1106.00                           00   
23338  57599423036231  Q  @F I      14  1106.00                           00   
23339  57599423068858  Q  @F I      15  1106.00                           00   
23340  57599435529251  Q  @F       100  1105.75                           00   
23341  57599435955263  Q  @F       100  1105.75                           00   
23342  57599436053455  Q  @F I       4  1105.75                           00   
23343  57599439722596  Q  @F I      96  1105.75                           00   
23344  57599439729226  Q  @F I       4  1105.75                           00   
23345  57599439735436  Q  @F I      25  1105.75                           00   
23346  57599498297091  Q  @F I       5  1105.73                           00   
23347  57599505061377  Q  @F       100  1105.58                           00   
23348  57599529844975  Q  @F I       1  1105.41                           00   
23349  57599529851797  Q  @F I      99  1105.39                           00   
23350  57599529

In [15]:
cleanedData[(cleanedData['hour_min_col'] > 9.6) & (cleanedData['hour_min_col'] < 9.7)]

utcsec ex  cond  volume    price TradeStopStockIndicator corr  \
1774  34621200075630  Q  @F I       6  1124.98                           00   
1775  34621200080193  Q  @F I      10  1125.00                           00   
1776  34621200192318  Q  @F I       5  1125.00                           00   
1777  34621203396369  Q  @F I      13  1125.52                           00   
1778  34621204241407  Q  @F I       7  1125.52                           00   
1779  34624846143673  Q  @F I      20  1126.00                           00   
1780  34624846147812  Q  @F I       1  1126.00                           00   
1781  34624847803554  Q  @F I       1  1126.41                           00   
1782  34624849420780  Q  @F I       9  1126.50                           00   
1783  34624849670690  Q  @  I      14  1126.50                           00   
1784  34624926901394  Q  @  I       1  1126.72                           00   
1785  34625779328397  Q  @F       100  1126.16                           00   
1786  34625779332926  Q  @F I      18  1125.99                           00   
1787  34625845906461  Q  @  I       7  1125.63                           00   
1788  34632023661990  Q  @F I      14  1126.05                           00   
1789  34632023671812  Q  @F I       6  1126.05                           00   
1790  34632641621318  Q  @F I       6  1127.00                           00   
1791  34632641658596  Q  @  I      29  1127.00                           00   
1792  34635979901166  Q  @  I      10  1127.11                           00   
1793  34636761538359  Q  @  I       5  1127.25                           00   
1794  34638514064731  Q  @F I      35  1127.08                           00   
1795  34640589911641  Q  @  I      22  1127.40                           00   
1796  34641560817358  Q  @F I       8  1127.21                           00   
1797  34642737486872  Q  @  I       2  1127.60                           00   
1798  34645223471613  Q  @  I       1  1127.42                           00   
1799  34645506031224  Q  @  I       1  1127.00                           00   
1800  34646776204263  Q  @  I       1  1127.34                           00   
1801  34646857760463  Q  @  I       5  1127.46                           00   
1802  34647130703820  Q  @  I       5  1127.56                           00   
1803  34649283729079  Q  @  I      10  1127.75                           00   
...              ... ..   ...     ...      ...                     ...  ...   
2241  34892392736081  Q  @  I      24  1124.98                           00   
2242  34892392749912  Q  @  I       5  1124.98                           00   
2243  34892392754433  Q  @F I      71  1124.98                           00   
2244  34892393074577  Q  @F I      17  1124.98                           00   
2245  34892393177370  Q  @  I       8  1124.98                           00   
2246  34892398474663  Q  @F I       4  1125.15                           00   
2247  34901526893316  Q  @  I       5  1124.83                           00   
2248  34902878523496  Q  @F I       1  1124.13                           00   
2249  34905963391822  Q  @  I      10  1125.00                           00   
2250  34905963426757  Q  @  I      10  1125.00                           00   
2251  34907904862983  Q  @F I      66  1125.15                           00   
2252  34907904869573  Q  @F I      34  1125.15                           00   
2253  34907904873945  Q  @F       100  1125.18                           00   
2254  34907904877519  Q  @F I      66  1125.20                           00   
2255  34907905141367  Q  @F I      34  1125.20                           00   
2256  34907905144281  Q  @F       100  1125.20                           00   
2257  34907905547103  Q  @F I       1  1125.21                           00   
2258  34907905974025  Q  @F I      75  1125.33                           00   
2259  34907905980600  Q  @F I      25  1125.33                  

In [16]:
cleanedData.groupby(['Date','time_group'])[['price','Timestamp']].first() # .last()

price                  Timestamp
Date     time_group                                    
20200401 0           1122.26 2020-04-01 09:30:00.012706
         1           1124.72 2020-04-01 09:40:02.376757
         2           1120.13 2020-04-01 09:50:00.514164
         3           1115.35 2020-04-01 10:00:00.001645
         4           1124.33 2020-04-01 10:10:03.030533
         5           1124.81 2020-04-01 10:20:10.697902
         6           1122.58 2020-04-01 10:30:03.432125
         7           1127.67 2020-04-01 10:40:04.582640
         8           1125.80 2020-04-01 10:50:05.461097
         9           1127.00 2020-04-01 11:00:10.846559
         10          1128.12 2020-04-01 11:10:01.552534
         11          1126.27 2020-04-01 11:20:06.754553
         12          1121.14 2020-04-01 11:30:02.422136
         13          1119.04 2020-04-01 11:40:00.895746
         14          1117.15 2020-04-01 11:50:09.753210
         15          1117.68 2020-04-01 12:00:01.142005
         16          1115.74 2020-04-01 12:10:05.074493
         17          1114.14 2020-04-01 12:20:07.501602
         18          1111.49 2020-04-01 12:30:04.166204
         19          1106.45 2020-04-01 12:40:05.897464
         20          1105.54 2020-04-01 12:50:12.640710
         21          1108.44 2020-04-01 13:00:00.130828
         22          1110.52 2020-04-01 13:10:06.700589
         23          1110.99 2020-04-01 13:20:13.416221
         24          1111.00 2020-04-01 13:30:12.778582
         25          1111.65 2020-04-01 13:40:12.401546
         26          1108.00 2020-04-01 13:50:08.091597
         27          1111.77 2020-04-01 14:00:00.018328
         28          1111.88 2020-04-01 14:10:00.620321
         29          1109.05 2020-04-01 14:20:00.765345
         30          1108.54 2020-04-01 14:30:00.382845
         31          1109.73 2020-04-01 14:40:00.265699
         32          1109.00 2020-04-01 14:50:19.920914
         33          1105.10 2020-04-01 15:00:00.516835
         34          1105.40 2020-04-01 15:10:15.900661
         35          1104.05 2020-04-01 15:20:02.029433
         36          1100.76 2020-04-01 15:30:03.342836
         37          1097.50 2020-04-01 15:40:02.460831
         38          1106.62 2020-04-01 15:50:00.019019

In [17]:
OHLC = cleanedData.groupby(['Date','time_group'])[['price']].agg(['first', 'max', 'min', 'last'])
OHLC.values.shape

(39, 4)

In [18]:
OHLC.values[:5], OHLC.values[-5:]

(array([[1122.26, 1128.7 , 1114.79, 1124.52],
        [1124.72, 1127.85, 1118.26, 1120.29],
        [1120.13, 1121.68, 1115.18, 1115.55],
        [1115.35, 1126.  , 1114.3 , 1124.3 ],
        [1124.33, 1129.31, 1123.  , 1124.66]]),
 array([[1105.4 , 1105.71, 1101.8 , 1104.  ],
        [1104.05, 1104.05, 1100.36, 1100.69],
        [1100.76, 1101.28, 1097.44, 1097.88],
        [1097.5 , 1110.68, 1097.21, 1106.87],
        [1106.62, 1110.97, 1102.43, 1105.62]]))

In [19]:
# set up as function
def candleCreateNP_vect(verbose=True):
        
    cleanedData['hour_min_col'] = cleanedData['Hour'] + cleanedData['Minute']/60
    if verbose:
        print(f"min and max of new hour_min_col: \
              {cleanedData['hour_min_col'].min()}, {cleanedData['hour_min_col'].max()}")
              
    # setup time_bins to group each timestamp
    time_bins = np.arange(9.5, 16+step/60, step/60)
              
    # put each timestamp into a bucket according to time_bins defined by the step variable
    cleanedData['time_group'] = pd.cut(cleanedData['hour_min_col'], bins=time_bins, right=False, labels=False)
    
    # group by date and time_group, extract price, take it first, max, min, last (open, high, low, close)
    OHLC = cleanedData.groupby(['Date','time_group'])[['price']].agg(['first', 'max', 'min', 'last'])              
    
    # return as numpy if preferred
    return OHLC.values

### Compare timing once

In [20]:
import time
a = time.time()
candleNP1 = candleCreateNP()
b = time.time()
print(b-a)

a = time.time()
candleNP2 = candleCreateNP_vect()
b = time.time()
print(b-a)

0.15100860595703125
min and max of new hour_min_col:               9.5, 15.983333333333333
0.015001058578491211


In [21]:
# Make sure they are equal
(candleNP1.shape == candleNP2.shape), \
(candleNP1 == candleNP2).all(), \
np.array_equal(candleNP1, candleNP2)

(True, True, True)

### Multiple time-it runs

In [28]:
# Aggregate data in candle sticks
%timeit candleNP1 = candleCreateNP()
%timeit candleNP2 = candleCreateNP_vect(verbose=False)

118 ms ± 584 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
13.8 ms ± 21.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
